on: [push, pull_request]
jobs:
  xcodetest:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: '/Applications/Xcode_${{ matrix.xcode }}.app'
    strategy:
      matrix:
        # xcode 12.5 is not available yet, as it runs on macos-11 and macos 11 is in a private pool
        # https://github.com/actions/virtual-environments/issues/2486
        xcode: ['10.3', '11.3.1', '11.6', '12_beta', '12.4']
    steps:
      - uses: actions/checkout@v2
      - run: rm -fr IntegrationTests  # swift package will generate wrong package
      - run: swift package generate-xcodeproj
      - run: xcodebuild test -scheme Spectre-Package
      - run: xcodebuild test -scheme Spectre-Package -sdk iphonesimulator -destination "name=iPhone 8"
